language: java
jdk:
  - openjdk8

env:
  - CI=1
script:
  - cd crawler
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B

after_failure:
  - cat target/surefire-reports/*.txt