version: "3"
services:
  web:
    build: .
    ports:
      - 8081:8080
    depends_on:
      - db
      - solr
    environment:
      - DOCKER_COMPOSE=1
  db:
    container_name: unidisk_db
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: unidisk
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 8082:8080

  solr:
    image: solr:8
    ports:
      - 8983:8983
    volumes:
      - solr_data:/var/solr
    command:
      - solr-precreate
      - unidisc

  recommendation:
    build: ./recommendation
    ports:
      - 8083:8000

volumes:
  solr_data:
