version: "3"

services:
  #https://github.com/docker-solr/docker-solr
  solr:
    image: solr:8
    ports:
      - "8983:8983"
    volumes:
      - data:/var/solr
    command:
      - solr-precreate
      - gettingstarted

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    image: tomcat
    ports:
      - "8081:8081"
    volumes:
      - ./target/unidisk.war:/usr/local/tomcat/webapps/ROOT.war
      - ./target/unidisk:/usr/local/tomcat/webapps/ROOT

volumes:
  data:
