version: "3"
services:
  web:
    build: .
    ports:
      - 8081:8080
    depends_on:
      - db
  db:
    container_name: unidisk_db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: unidisk
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 8082:8080

volumes:
  unidisk_db_data:
